Contact.create!([
  {first_name: "Wava", last_name: "Wisozk", email: "wisozk_wava@yahoo.com", phone_number: "(949) 035-8201 x546", middle_name: nil, bio: nil},
  {first_name: "Lowell", last_name: "Sauer", email: "sauer_lowell@yahoo.com", phone_number: "(712) 461-9755", middle_name: nil, bio: nil},
  {first_name: "Demarco", last_name: "Ryan", email: "ryan.demarco@gmail.com", phone_number: "886.364.8023", middle_name: nil, bio: nil},
  {first_name: "Danielle", last_name: "Lynch", email: "danielle_lynch@gmail.com", phone_number: "121.056.3043 x437", middle_name: nil, bio: nil},
  {first_name: "Regan", last_name: "Thiel", email: "regan.thiel@hotmail.com", phone_number: "287-488-7939", middle_name: nil, bio: nil},
  {first_name: "Jarrell", last_name: "Volkman", email: "volkman.jarrell@hotmail.com", phone_number: "989.414.1308 x9366", middle_name: nil, bio: nil},
  {first_name: "Terrell", last_name: "Sanford", email: "sanford.terrell@yahoo.com", phone_number: "304.755.7562", middle_name: nil, bio: nil},
  {first_name: "Darion", last_name: "Blanda", email: "blanda_darion@yahoo.com", phone_number: "1-456-999-0517", middle_name: nil, bio: nil},
  {first_name: "Moses", last_name: "Monahan", email: "moses_monahan@gmail.com", phone_number: "(840) 876-2337", middle_name: nil, bio: nil},
  {first_name: "Kimberly", last_name: "Connelly", email: "kimberly.connelly@yahoo.com", phone_number: "1-394-937-9717 x645", middle_name: nil, bio: nil},
  {first_name: "Deontae", last_name: "Walker", email: "deontae_walker@hotmail.com", phone_number: "795.695.4342 x163", middle_name: nil, bio: nil},
  {first_name: "Javier", last_name: "Bernier", email: "bernier_javier@yahoo.com", phone_number: "651.119.8545", middle_name: nil, bio: nil},
  {first_name: "Jaylin", last_name: "Spinka", email: "jaylin_spinka@hotmail.com", phone_number: "1-393-100-3783 x4713", middle_name: nil, bio: nil},
  {first_name: "Dustin", last_name: "Morar", email: "morar_dustin@hotmail.com", phone_number: "372-040-4962", middle_name: nil, bio: nil},
  {first_name: "Christopher", last_name: "Maggio", email: "maggio_christopher@hotmail.com", phone_number: "465-928-5433 x5024", middle_name: nil, bio: nil},
  {first_name: "Wilton", last_name: "Hahn", email: "hahn_wilton@hotmail.com", phone_number: "1-254-420-2902", middle_name: nil, bio: nil},
  {first_name: "Thurman", last_name: "Green", email: "green.thurman@gmail.com", phone_number: "869.857.4365", middle_name: nil, bio: nil},
  {first_name: "Lacy", last_name: "Kuhn", email: "kuhn.lacy@gmail.com", phone_number: "543-124-0846 x56871", middle_name: nil, bio: nil},
  {first_name: "Gaylord", last_name: "Emmerich", email: "gaylord_emmerich@gmail.com", phone_number: "660.849.4374 x0617", middle_name: nil, bio: nil},
  {first_name: "Milo", last_name: "Schinner", email: "schinner.milo@gmail.com", phone_number: "1-544-978-9772 x64802", middle_name: nil, bio: nil},
  {first_name: "Shanna", last_name: "O'Keefe", email: "keefe.shanna.o@gmail.com", phone_number: "(362) 202-7599 x78021", middle_name: nil, bio: nil},
  {first_name: "Herminio", last_name: "Schumm", email: "schumm_herminio@gmail.com", phone_number: "900-563-9562", middle_name: nil, bio: nil},
  {first_name: "Bud", last_name: "Kub", email: "bud_kub@gmail.com", phone_number: "263-077-5576", middle_name: nil, bio: nil},
  {first_name: "Layla", last_name: "Turcotte", email: "turcotte.layla@yahoo.com", phone_number: "(222) 718-8975 x286", middle_name: nil, bio: nil},
  {first_name: "Hershel", last_name: "Marks", email: "marks.hershel@gmail.com", phone_number: "353.316.6961", middle_name: nil, bio: nil},
  {first_name: "Raul", last_name: "Reichel", email: "reichel.raul@gmail.com", phone_number: "1-604-310-8154 x275", middle_name: nil, bio: nil},
  {first_name: "Murphy", last_name: "Windler", email: "murphy_windler@hotmail.com", phone_number: "878.679.6131 x78075", middle_name: nil, bio: nil},
  {first_name: "Elda", last_name: "Bauch", email: "elda.bauch@hotmail.com", phone_number: "473.067.8094 x29075", middle_name: nil, bio: nil},
  {first_name: "Donald", last_name: "Bartell", email: "bartell_donald@hotmail.com", phone_number: "(410) 875-9589 x6593", middle_name: nil, bio: nil},
  {first_name: "Valentin", last_name: "O'Hara", email: "valentin.o.hara@yahoo.com", phone_number: "1-362-365-3103", middle_name: nil, bio: nil},
  {first_name: "Jonathon", last_name: "Goldner", email: "jonathon.goldner@yahoo.com", phone_number: "977.664.6217", middle_name: nil, bio: nil},
  {first_name: "Opal", last_name: "Pagac", email: "opal.pagac@hotmail.com", phone_number: "501.347.9604 x55263", middle_name: nil, bio: nil},
  {first_name: "Orpha", last_name: "Kessler", email: "kessler.orpha@gmail.com", phone_number: "795-008-0351 x5206", middle_name: nil, bio: nil},
  {first_name: "Keshaun", last_name: "Stokes", email: "keshaun.stokes@gmail.com", phone_number: "1-966-025-8590", middle_name: nil, bio: nil},
  {first_name: "Rylan", last_name: "Turcotte", email: "turcotte_rylan@hotmail.com", phone_number: "1-984-782-4075 x96319", middle_name: nil, bio: nil},
  {first_name: "Antonietta", last_name: "Beer", email: "antonietta_beer@gmail.com", phone_number: "857-864-5435 x6058", middle_name: nil, bio: nil},
  {first_name: "Delbert", last_name: "Lebsack", email: "lebsack.delbert@yahoo.com", phone_number: "994.218.2452 x382", middle_name: nil, bio: nil},
  {first_name: "Lexi", last_name: "Walter", email: "lexi_walter@hotmail.com", phone_number: "(112) 039-8312 x277", middle_name: nil, bio: nil},
  {first_name: "Kurtis", last_name: "Casper", email: "casper.kurtis@yahoo.com", phone_number: "(514) 530-2174", middle_name: nil, bio: nil},
  {first_name: "Joshuah", last_name: "Reinger", email: "joshuah_reinger@yahoo.com", phone_number: "1-954-314-1401", middle_name: nil, bio: nil},
  {first_name: "Ila", last_name: "Schumm", email: "schumm.ila@yahoo.com", phone_number: "281.548.2851", middle_name: nil, bio: nil},
  {first_name: "Mattie", last_name: "Bartell", email: "mattie_bartell@gmail.com", phone_number: "314-387-0880 x3820", middle_name: nil, bio: nil},
  {first_name: "Julia", last_name: "Rippin", email: "rippin_julia@yahoo.com", phone_number: "(289) 647-4053", middle_name: nil, bio: nil},
  {first_name: "Aurore", last_name: "Simonis", email: "aurore_simonis@gmail.com", phone_number: "(195) 477-6212", middle_name: nil, bio: nil},
  {first_name: "Genesis", last_name: "Considine", email: "genesis_considine@yahoo.com", phone_number: "1-986-098-5067", middle_name: nil, bio: nil},
  {first_name: "Ozzie", last_name: "Breitenberg", email: "ozzie.breitenberg@gmail.com", phone_number: "444.811.3768", middle_name: nil, bio: nil},
  {first_name: "Grace", last_name: "Feil", email: "grace_feil@yahoo.com", phone_number: "920.983.3668 x6654", middle_name: nil, bio: nil},
  {first_name: "Jake", last_name: "Heidenreich", email: "jake.heidenreich@hotmail.com", phone_number: "290.198.3304", middle_name: nil, bio: nil},
  {first_name: "Fae", last_name: "Turcotte", email: "fae.turcotte@hotmail.com", phone_number: "1-684-790-4884", middle_name: nil, bio: nil},
  {first_name: "Pearline", last_name: "Strosin", email: "pearline_strosin@yahoo.com", phone_number: "1-343-782-2267 x17047", middle_name: nil, bio: nil},
  {first_name: "Jammie", last_name: "Douglas", email: "douglas_jammie@hotmail.com", phone_number: "527-226-5589 x42079", middle_name: nil, bio: nil},
  {first_name: "Martine", last_name: "Veum", email: "veum_martine@hotmail.com", phone_number: "1-666-993-7105", middle_name: nil, bio: nil},
  {first_name: "Aida", last_name: "Treutel", email: "aida_treutel@gmail.com", phone_number: "572-209-0387 x3358", middle_name: nil, bio: nil},
  {first_name: "Liza", last_name: "Corwin", email: "corwin_liza@hotmail.com", phone_number: "1-968-427-2849 x648", middle_name: nil, bio: nil},
  {first_name: "Antonette", last_name: "Mertz", email: "antonette_mertz@gmail.com", phone_number: "(747) 775-5157 x312", middle_name: nil, bio: nil},
  {first_name: "Webster", last_name: "Nolan", email: "webster.nolan@hotmail.com", phone_number: "551.417.8031 x19524", middle_name: nil, bio: nil},
  {first_name: "Shemar", last_name: "Nicolas", email: "nicolas.shemar@hotmail.com", phone_number: "971-963-2412 x3564", middle_name: nil, bio: nil},
  {first_name: "Josiane", last_name: "Lindgren", email: "lindgren_josiane@hotmail.com", phone_number: "436.594.7603", middle_name: nil, bio: nil},
  {first_name: "Cassandra", last_name: "Bogisich", email: "bogisich.cassandra@yahoo.com", phone_number: "(320) 060-8937 x07063", middle_name: nil, bio: nil},
  {first_name: "Abdullah", last_name: "Douglas", email: "abdullah_douglas@yahoo.com", phone_number: "901.461.3119 x6183", middle_name: nil, bio: nil},
  {first_name: "Araceli", last_name: "Frami", email: "frami_araceli@gmail.com", phone_number: "425-377-7791 x43608", middle_name: nil, bio: nil},
  {first_name: "Cecil", last_name: "Jacobson", email: "cecil.jacobson@gmail.com", phone_number: "859-321-6180 x09782", middle_name: nil, bio: nil},
  {first_name: "Abby", last_name: "Bernhard", email: "bernhard.abby@hotmail.com", phone_number: "420.210.4146 x234", middle_name: nil, bio: nil},
  {first_name: "Walker", last_name: "Brekke", email: "walker.brekke@hotmail.com", phone_number: "886-825-3091", middle_name: nil, bio: nil},
  {first_name: "Chadrick", last_name: "Bauch", email: "bauch_chadrick@hotmail.com", phone_number: "168-430-2550 x3320", middle_name: nil, bio: nil},
  {first_name: "Jason", last_name: "Borer", email: "borer.jason@gmail.com", phone_number: "774.308.4024 x72349", middle_name: nil, bio: nil},
  {first_name: "Winston", last_name: "Breitenberg", email: "breitenberg_winston@yahoo.com", phone_number: "685.213.1623", middle_name: nil, bio: nil},
  {first_name: "Raymundo", last_name: "Koss", email: "raymundo_koss@hotmail.com", phone_number: "793-774-1111 x1582", middle_name: nil, bio: nil},
  {first_name: "Delilah", last_name: "Kirlin", email: "kirlin.delilah@yahoo.com", phone_number: "1-100-606-2357", middle_name: nil, bio: nil},
  {first_name: "Hanna", last_name: "Padberg", email: "hanna_padberg@yahoo.com", phone_number: "1-227-712-5352 x79865", middle_name: nil, bio: nil},
  {first_name: "Teresa", last_name: "Rohan", email: "teresa_rohan@yahoo.com", phone_number: "(589) 242-8685 x9669", middle_name: "", bio: "I like chocolates. I like traveling"},
  {first_name: "Ubaldo", last_name: "Muller", email: "ubaldo.muller@hotmail.com", phone_number: "409-590-1897 x870", middle_name: nil, bio: nil},
  {first_name: "Jalen", last_name: "Jerde", email: "jerde.jalen@hotmail.com", phone_number: "315-246-4237 x57163", middle_name: nil, bio: nil},
  {first_name: "Isabell", last_name: "Bergnaum", email: "bergnaum.isabell@hotmail.com", phone_number: "1-783-727-9045", middle_name: nil, bio: nil},
  {first_name: "Andres", last_name: "Flatley", email: "andres.flatley@hotmail.com", phone_number: "1-885-039-3919", middle_name: nil, bio: nil},
  {first_name: "Rashawn", last_name: "Eichmann", email: "rashawn.eichmann@yahoo.com", phone_number: "1-486-238-0084 x027", middle_name: nil, bio: nil},
  {first_name: "Derek", last_name: "Bernier", email: "derek.bernier@gmail.com", phone_number: "1-367-228-4549 x35591", middle_name: nil, bio: nil},
  {first_name: "Malinda", last_name: "McClure", email: "malinda_mcclure@hotmail.com", phone_number: "(578) 946-3947", middle_name: nil, bio: nil},
  {first_name: "Evalyn", last_name: "White", email: "evalyn_white@gmail.com", phone_number: "476-132-8319", middle_name: nil, bio: nil},
  {first_name: "Kim", last_name: "Volkman", email: "kim.volkman@hotmail.com", phone_number: "1-509-580-0927 x591", middle_name: nil, bio: nil},
  {first_name: "Reina", last_name: "Hills", email: "reina.hills@gmail.com", phone_number: "682.460.0625 x3873", middle_name: nil, bio: nil},
  {first_name: "Vivian", last_name: "Kuhlman", email: "vivian_kuhlman@gmail.com", phone_number: "170-815-0144 x65537", middle_name: nil, bio: nil},
  {first_name: "Sally", last_name: "Mosciski", email: "mosciski.sally@gmail.com", phone_number: "(169) 592-0030 x883", middle_name: nil, bio: nil},
  {first_name: "Chad", last_name: "Mohr", email: "mohr.chad@yahoo.com", phone_number: "392.327.4344 x5943", middle_name: nil, bio: nil},
  {first_name: "Rashawn", last_name: "Crona", email: "crona.rashawn@gmail.com", phone_number: "672.215.9640", middle_name: nil, bio: nil},
  {first_name: "Norbert", last_name: "Jerde", email: "jerde.norbert@yahoo.com", phone_number: "1-290-341-0037", middle_name: nil, bio: nil},
  {first_name: "Joanne", last_name: "Fisher", email: "fisher.joanne@yahoo.com", phone_number: "(632) 208-3908", middle_name: nil, bio: nil},
  {first_name: "Ruth", last_name: "Erdman", email: "ruth_erdman@gmail.com", phone_number: "133-087-0344 x370", middle_name: nil, bio: nil},
  {first_name: "Brittany", last_name: "Leannon", email: "leannon.brittany@hotmail.com", phone_number: "(313) 260-8500 x76228", middle_name: nil, bio: nil},
  {first_name: "Maiya", last_name: "Eichmann", email: "eichmann.maiya@gmail.com", phone_number: "(526) 390-3004 x350", middle_name: nil, bio: nil},
  {first_name: "Muriel", last_name: "Miller", email: "miller.muriel@yahoo.com", phone_number: "(888) 000-3718 x6140", middle_name: nil, bio: nil},
  {first_name: "Jeramy", last_name: "Hansen", email: "jeramy.hansen@gmail.com", phone_number: "629.958.4353", middle_name: nil, bio: nil},
  {first_name: "Nia", last_name: "Hayes", email: "nia_hayes@yahoo.com", phone_number: "377-149-3619", middle_name: nil, bio: nil},
  {first_name: "Otho", last_name: "Volkman", email: "otho.volkman@yahoo.com", phone_number: "917.674.7014", middle_name: nil, bio: nil},
  {first_name: "Amaya", last_name: "McGlynn", email: "amaya_mcglynn@yahoo.com", phone_number: "544.060.8020 x099", middle_name: nil, bio: nil},
  {first_name: "Karina", last_name: "Homenick", email: "homenick.karina@gmail.com", phone_number: "(886) 140-2382 x52779", middle_name: nil, bio: nil},
  {first_name: "Adelia", last_name: "Wintheiser", email: "wintheiser_adelia@hotmail.com", phone_number: "446.427.1634", middle_name: nil, bio: nil},
  {first_name: "Patience", last_name: "Daniel", email: "patience.daniel@yahoo.com", phone_number: "866-513-6374 x946", middle_name: nil, bio: nil},
  {first_name: "Lauretta", last_name: "Ratke", email: "ratke_lauretta@hotmail.com", phone_number: "1-547-779-0076", middle_name: nil, bio: nil},
  {first_name: "Garrett", last_name: "Treutel", email: "treutel.garrett@yahoo.com", phone_number: "(111) 450-6678", middle_name: nil, bio: nil},
  {first_name: "Haenah", last_name: "Hwang", email: "haenahhwang@gmail.com", phone_number: "630-123-5557", middle_name: nil, bio: nil},
  {first_name: "Haenah", last_name: "Hwang", email: "haenahhwang@gmail.com", phone_number: "630-123-5557", middle_name: nil, bio: nil},
  {first_name: "Haenah", last_name: "Hwang", email: "haenahhwang@gmail.com", phone_number: "630-123-5557", middle_name: nil, bio: nil},
  {first_name: "Haenah", last_name: "Hwang", email: "haenahhwang@gmail.com", phone_number: "630-123-5557", middle_name: nil, bio: nil},
  {first_name: "Haenah", last_name: "Hwang", email: "haenahhwang@gmail.com", phone_number: "630-123-5557", middle_name: nil, bio: nil},
  {first_name: "Victor", last_name: "Lee", email: "victorchristopherlee@gmail.com", phone_number: "312-307-9070", middle_name: "Christopher", bio: "I like goldens"}
])
